version: '3'
services:
  backend:
    image: se-backend:latest
    ports:
      - 3002:3002
    # environment,overrideable with env var
    environment:
      ALLOW_CORS: ${RS_ALLOW_CORS:-true}
      CORS_HOST: ${RS_CORS_HOST:-http://localhost:3000}
      MYSQL_USER: ${RS_MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${RS_MYSQL_PASSWORD:-12345678}
      MYSQL_DATABASE: ${RS_MYSQL_DATABASE:-room_scrum}
      MYSQL_HOST: ${RS_MYSQL_HOST:-mysql}
      MYSQL_PORT: ${RS_MYSQL_PORT:-3306}
      MYSQL_TEST_DATAVASE: ${RS_MYSQL_TEST_DB:-test_db}
      PORT: ${RS_PORT:-3002}
      JWT_SECRET: ${RS_JWT_SECRET:-secret1234}
  mysql:
    image: mysql:8.0.19
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345678"
      MYSQL_DATABASE: "room_scrum"
      MYSQL_ROOT_PASSWORD: "1238943ujflefennace" 