version: '3'
services:
  
  backend:
    image: node:12.14-slim
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - .:/home/node/app
    entrypoint: ["sh", "-c", "yarn start:dev"]
    ports:
      - 3002:3002
    environment:
      ALLOW_CORS: "true"
      CORS_HOST: "http://localhost:3000"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345678"
      MYSQL_DATABASE: "room_scrum"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      PORT: "3002"
      JWT_SECRET: "secret1234"
  mysql:
    image: mysql:8.0.19
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345678"
      MYSQL_DATABASE: "room_scrum"
      MYSQL_ROOT_PASSWORD: "1238943ujflefennace" 