name: CI
on:
  push:
    branches:
      - master
      - dev
      - test # for testing CI w/o messing up dev branch
  
jobs:   
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: EC2 deploy
      env:
        KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        ADDRESS: ${{ secrets.EC2_CONNECTION_STRING }}
        APPNAME: "se-project-backend"
        BRANCH: ${GITHUB_REF/refs\/heads\//}    
      run: |
        echo "$KEY" >> private_key.cer &&
        chmod 600 private_key.cer &&
        ssh -oStrictHostKeyChecking=no -i private_key.cer 52.220.252.160 \ 
        "
          export APPNAME=$APPNAME;
          export BRANCH=$BRANCH;
          bash --login -i -c $(cat build.sh);
        " 
