name: CI
on:
  push:
    branches:
      - master
      - dev
      - test # for testing CI w/o messing up dev branch
    
jobs:   
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: EC2 deploy
      env:
        KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        ADDRESS: ${{ secrets.EC2_CONNECTION_STRING }}
        PROJECT_DIR: ~/Projects/room-scrum-backend

      run: |
        export BRANCH=${GITHUB_REF/refs\/heads\//};
        echo "$KEY" >> private_key.cer &&
        chmod 600 private_key.cer &&
        # shell and run cmd
        ssh -oStrictHostKeyChecking=no -i private_key.cer $ADDRESS "
          export APPNAME=$APPNAME;
          export BRANCH=$BRANCH;
          
          bash --login -i '
            mkdir -p $PROJECT_DIR &&
            cd $PROJECT_DIR &&
            git checkout $BRANCH && git pull &&
            . .env &&
            docker-compose build &&
            docker-compose up backend;
          ';
        " 
